
/****** Object:  StoredProcedure [usp_NewBookLibrary]    Script Date: 11/12/2017 5:15:26 PM ******/


USE LMS
GO


CREATE PROCEDURE  [usp_NewBookLibrary] 

AS
BEGIN




-- USE SCHEMA BOOKDATA

CREATE TABLE BOOKDATA.BOOK (
BookID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
Title VARCHAR(50)CONSTRAINT unq_title UNIQUE CONSTRAINT nonull_title NOT NULL,
PublisherName VARCHAR(50) NOT NULL
)

CREATE TABLE BOOKDATA.BOOK_AUTHORS (
BookID INT NOT NULL,
AuthorName VARCHAR(50) NOT NULL
)


CREATE TABLE BOOKDATA.PUBLISHER (
Name VARCHAR(50) NOT NULL,
Address VARCHAR(50) NOT NULL,
Phone VARCHAR(50) NOT NULL
)

--- USE SCHEMA LIBRARYDATA

CREATE TABLE LIBRARYDATA.LIBRARY_BRANCH (
BranchID INT PRIMARY KEY NOT NULL ,
BranchName VARCHAR(20) NOT NULL,
Address VARCHAR(50) NOT NULL
)

CREATE TABLE LIBRARYDATA.BORROWER(
CardNo INT PRIMARY KEY NOT NULL  ,
Name VARCHAR(50) NOT NULL,
Address VARCHAR(50) NOT NULL,
Phone VARCHAR(15) NOT NULL
)

CREATE TABLE LIBRARYDATA.BOOK_LOANS (
BookID INT NOT NULL ,
BranchID INT NOT NULL ,
CardNo  INT NOT NULL,
DueDate DATE NOT NULL
)



CREATE TABLE LIBRARYDATA.BOOK_COPIES (
BookID INT NOT NULL ,
BranchID INT NOT NULL ,
No_of_Copies INT NOT NULL
)

;
END
