USE [LMS]
GO
/****** Object:  StoredProcedure [dbo].[usp_NewBookLibrary]    Script Date: 11/12/2017 5:15:26 PM ******/


--USE MASTER
--CREATE DATABASE LMS
--GO



--Create Schema [BOOKDATA] Authorization [dbo]


--Create Schema [LIBRARYDATA] Authorization [dbo]

CREATE PROCEDURE [dbo].[dbo.usp_NewBookLibrary]
AS
BEGIN

-- USE SCHEMA BOOKDATA

CREATE TABLE BOOKDATA.BOOK (
BookID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
Title VARCHAR(50)CONSTRAINT unq_title UNIQUE CONSTRAINT nonull_title NOT NULL,
PublisherName VARCHAR(50) NOT NULL
)

CREATE TABLE BOOKDATA.BOOK_AUTHORS (
BookID INT NOT NULL CONSTRAINT fk_book_id FOREIGN KEY REFERENCES BOOKDATA.Book(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
AuthorName VARCHAR(50) NOT NULL
)


CREATE TABLE BOOKDATA.PUBLISHER (
Name VARCHAR(50) NOT NULL,
Address VARCHAR(50) NOT NULL,
Phone VARCHAR(50) NOT NULL
)

--- USE SCHEMA LIBRARYDATA

CREATE TABLE LIBRARYDATA.LIBRARY_BRANCH (
BranchID INT PRIMARY KEY NOT NULL IDENTITY (100,1),
BranchName VARCHAR(20) NOT NULL,
Address VARCHAR(50) NOT NULL
)

CREATE TABLE LIBRARYDATA.BORROWER(
CardNo INT PRIMARY KEY NOT NULL IDENTITY (2500,1),
Name VARCHAR(50) NOT NULL,
Address VARCHAR(50) NOT NULL,
Phone VARCHAR(15) NOT NULL
)

CREATE TABLE LIBRARYDATA.BOOK_LOANS (
BookID INT NOT NULL CONSTRAINT fk_book_id FOREIGN KEY REFERENCES BOOKDATA.Book(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
BranchID INT NOT NULL CONSTRAINT fk_branch_id FOREIGN KEY REFERENCES LIBRARYDATA.LIBRARY_BRANCH(BranchID) ON UPDATE CASCADE ON DELETE CASCADE,
CardNo  INT NOT NULL CONSTRAINT fk_cardno FOREIGN KEY REFERENCES LIBRARYDATA.Borrower(cardno) ON UPDATE CASCADE ON DELETE CASCADE,
DueDate DATE NOT NULL
)



CREATE TABLE LIBRARYDATA.BOOK_COPIES (
BookID INT NOT NULL CONSTRAINT fk_bookid FOREIGN KEY REFERENCES BOOKDATA.Book(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
BranchID INT NOT NULL CONSTRAINT fk_branchid FOREIGN KEY REFERENCES LIBRARYDATA.LIBRARY_BRANCH(BranchID) ON UPDATE CASCADE ON DELETE CASCADE,
No_of_Copies INT NOT NULL
)

END 

